version: "2"

services:
  php-apache:
    build:
        context: ./bin/php-apache
    container_name: dev_apache
    ports:
        - 80:80
    volumes:
        - ./www:/var/www/html
    links:
        - mysql
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    restart: 'always'
    ports:
      - 3306:3306
    volumes: 
      - .volumes/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - 8080:80